version: '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis

    orderdb:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu

    rabbitmq:
        image: rabbitmq:3-management-alpine

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: src/Catalog/Catalog.API/Dockerfile

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: src/Basket/Basket.API/Dockerfile


    ordering.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
            context: .
            dockerfile: src/Ordering/Ordering.API/Dockerfile


    api.gateway:
        image: ${DOCKER_REGISTRY-}apigateway
        build:
            context: .
            dockerfile: src/ApiGateway/API.Gateway/Dockerfile


    aspnetwebmvc:
        image: ${DOCKER_REGISTRY-}aspnetwebmvc
        build:
            context: .
            dockerfile: src/WebApp/AspnetWebMvc/Dockerfile

